#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install emacs tmux mosh zsh git wget chromium-browser gnome-tweak-tool chrome-gnome-shell -y


# paper_theme
sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update
sudo apt-get install paper-icon-theme
sudo apt-get install paper-cursor-theme
sudo apt-get install paper-gtk-theme


# spacemacs()
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
emacs -nw &

# Numix_theme()
##gsettings set org.gnome.desktop.interface gtk-theme "Numix"
##gsettings set org.gnome.desktop.wm.preferences theme "Numix"

# oh_my_zsh()
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# swap_ctrl_caps()
##echo "clear lock" > /home/km4sh/.Xmodmap
##echo "clear control" >> /home/km4sh/.Xmodmap
##echo "keycode 66 = Control_L" >> /home/km4sh/.Xmodmap
##echo "add control = Control_L Control_R" >> /home/km4sh/.Xmodmap

# fonts()
wget https://gist.githubusercontent.com/lucasdavila/3875946/raw/1c100cae16a06bef154af0f290d665405b554b3b/install_source_code_pro.sh
sudo chmod +x install_source_code_pro.sh
sudo ./install_source_code_pro.sh
rm -f install_source_code_pro.sh

sudo add-apt-repository universe
sudo apt install fonts-firacode

reboot
