#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install emacs tmux curl mosh zsh git wget chromium-browser gnome-tweak-tool chrome-gnome-shell -y


# paper_theme
sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update
sudo apt-get install paper-icon-theme
sudo apt-get install paper-cursor-theme
sudo apt-get install paper-gtk-theme

# zero_tier()
curl -s https://install.zerotier.com/ | sudo bash

# spacemacs()
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
rm -f .spacemacs
wget https://github.com/mattma9209/km4sh4ubuntu/blob/master/.spacemacs
emacs -nw &

# Numix_theme()
##gsettings set org.gnome.desktop.interface gtk-theme "Numix"
##gsettings set org.gnome.desktop.wm.preferences theme "Numix"

# oh_my_zsh()
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# swap_ctrl_caps()
##echo "clear lock" > /home/km4sh/.Xmodmap
##echo "clear control" >> /home/km4sh/.Xmodmap
##echo "keycode 66 = Control_L" >> /home/km4sh/.Xmodmap
##echo "add control = Control_L Control_R" >> /home/km4sh/.Xmodmap

# fonts()
##source code pro
curl -L https://gist.githubusercontent.com/lucasdavila/3875946/raw/1c100cae16a06bef154af0f290d665405b554b3b/install_source_code_pro.sh | sudo bash
##fira code 
sudo add-apt-repository universe
sudo apt install fonts-firacode

reboot
